// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-bio.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_bio_default = defineTool({
  name: "get_bio",
  title: "Get bio",
  description: "Return Stephen Egar Ayim (Amasteve)'s professional biography and roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const bio = {
      name: "Stephen Egar Ayim",
      alias: "Amasteve",
      title: "Founder & CEO, Amasteve Integrated Services",
      publicRole: "Ward Rural Development Officer",
      location: "Ghana",
      summary: "Multidisciplinary digital professional working across digital marketing, front-end engineering, graphic design, videography, data analytics, blogging, social media management, and community development."
    };
    return {
      content: [{ type: "text", text: JSON.stringify(bio, null, 2) }],
      structuredContent: bio
    };
  }
});

// src/lib/mcp/tools/list-services.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var services = [
  { name: "Digital Marketing", description: "SEO, paid, and organic growth strategies." },
  { name: "Front-End Engineering", description: "Fast, accessible React & TypeScript interfaces." },
  { name: "Graphic Design", description: "Brand identity, editorial, and print systems." },
  { name: "Videography", description: "Cinematic direction, shooting, and post-production." },
  { name: "Data Analytics", description: "Insights that turn numbers into direction." },
  { name: "Blogging", description: "Long-form writing that earns attention and trust." },
  { name: "Social Media Management", description: "Strategy and management across platforms." },
  { name: "Community Development", description: "Rural mobilisation, programs, and civic impact." }
];
var list_services_default = defineTool2({
  name: "list_services",
  title: "List services",
  description: "List the professional services offered by Amasteve Integrated Services.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(services, null, 2) }],
    structuredContent: { services }
  })
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var projects = [
  { title: "Loslean \u2014 Brand Identity", discipline: "Graphic Design", year: 2025 },
  { title: "Editorial Web Platform", discipline: "Front-End Engineering", year: 2025 },
  { title: "Documentary Series", discipline: "Videography", year: 2024 },
  { title: "Growth Analytics Dashboard", discipline: "Data Analytics", year: 2024 }
];
var list_projects_default = defineTool3({
  name: "list_projects",
  title: "List featured projects",
  description: "List selected projects and portfolio work by Amasteve.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(projects, null, 2) }],
    structuredContent: { projects }
  })
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact = {
  email: "hello@amasteve.com",
  socials: {
    facebook: "https://facebook.com/amasteve",
    linkedin: "https://linkedin.com/in/amasteve",
    youtube: "https://youtube.com/@amasteve",
    instagram: "https://instagram.com/amasteve",
    x: "https://x.com/amasteve"
  },
  availability: "Select projects worldwide, based in Ghana."
};
var get_contact_info_default = defineTool4({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return Amasteve's email, social profiles, and current availability.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/tools/list-community-impact.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var stories = [
  {
    title: "Youth Digital Skills Initiative",
    description: "Introduced foundational design and marketing training to young people in the ward, opening pathways to online income."
  },
  {
    title: "Community Mobilisation",
    description: "Coordinated grassroots forums that surfaced local priorities and connected residents with district-level programs."
  },
  {
    title: "Storytelling for Development",
    description: "Documented rural voices through photo, video and long-form writing to attract advocacy and investment."
  }
];
var list_community_impact_default = defineTool5({
  name: "list_community_impact",
  title: "List community impact stories",
  description: "List community development stories from Amasteve's work as a Ward Rural Development Officer.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(stories, null, 2) }],
    structuredContent: { stories }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "amasteve-portfolio-mcp",
  title: "Amasteve Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for querying Stephen Egar Ayim (Amasteve)'s portfolio: bio, services, featured projects, community impact, and contact info.",
  tools: [get_bio_default, list_services_default, list_projects_default, get_contact_info_default, list_community_impact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
